# Generated by Django 6.0.1 on 2026-01-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="opening_balance_date",
            field=models.DateField(
                blank=True,
                help_text="Reference date for opening balance. If set, balance calculations start from this date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="booking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="booking_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="card_brand",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="owner_account",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="partner_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="partner_bank_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="partner_iban",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name="transaction",
            name="partner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_app",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sepa_scheme",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="valuation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="virtual_card_device",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="transaction",
            name="virtual_card_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(default="EUR", max_length=8),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
