# Generated by Django 6.0.1 on 2026-01-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "banking",
            "0002_alter_bankaccount_options_alter_transaction_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["user", "name"]},
        ),
    ]
