# Generated by Django 6.0.1 on 2026-01-14 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_alter_category_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("merchant_name", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("bi-weekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("next_expected_date", models.DateField()),
                ("last_occurrence_date", models.DateField()),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="0-1 confidence that this is truly recurring",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_ignored",
                    models.BooleanField(
                        default=False, help_text="User marked this as not relevant"
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True,
                        help_text="User's notes about this recurring transaction",
                    ),
                ),
                (
                    "similar_descriptions",
                    models.JSONField(
                        default=list,
                        help_text="All transaction descriptions that matched this pattern",
                    ),
                ),
                (
                    "transaction_ids",
                    models.JSONField(
                        default=list,
                        help_text="IDs of transactions that form this pattern",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_transactions",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-occurrence_count"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="banking_rec_user_id_2c05d9_idx",
                    ),
                    models.Index(
                        fields=["account", "is_active"],
                        name="banking_rec_account_42fd81_idx",
                    ),
                    models.Index(
                        fields=["frequency", "next_expected_date"],
                        name="banking_rec_frequen_8646f5_idx",
                    ),
                ],
                "unique_together": {("account", "description", "frequency")},
            },
        ),
    ]
