# Generated by Django 6.0.1 on 2026-01-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0004_recurringtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
