# Generated by Django 6.0.1 on 2026-01-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0005_transaction_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rates",
                    models.JSONField(
                        default=dict,
                        help_text="Exchange rates with USD as base (e.g., {EUR: 0.92, GBP: 0.79})",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of last successful rate fetch from API",
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True, help_text="API endpoint used for fetch"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Last error message if fetch failed"
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
            },
        ),
    ]
