# Generated by Django 6.0.1 on 2026-01-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0006_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata including import settings",
            ),
        ),
    ]
