# Generated by Django 6.0.1 on 2026-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0007_add_meta_to_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringtransaction",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="User-defined display name (falls back to merchant_name or description)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="description",
            field=models.CharField(
                help_text="Original description used for pattern matching",
                max_length=255,
            ),
        ),
    ]
