# Generated by Django 6.0.1 on 2026-01-21 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0008_recurringtransaction_display_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of import (e.g., 'csv', 'bank_api', 'manual')",
                        max_length=100,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        help_text="Original file name if imported from file",
                        max_length=255,
                    ),
                ),
                (
                    "total_transactions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of transactions in this import",
                    ),
                ),
                (
                    "successful_transactions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of successfully processed transactions",
                    ),
                ),
                (
                    "failed_transactions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of transactions that failed to process",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the import process",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this import was created",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "was_created",
                    models.BooleanField(
                        default=True,
                        help_text="True if transaction was created, False if updated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_transactions",
                        to="banking.import",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="banking.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="import",
            index=models.Index(
                fields=["account", "-created_at"], name="banking_imp_account_d7848b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="import",
            index=models.Index(
                fields=["user", "-created_at"], name="banking_imp_user_id_56ca5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importtransaction",
            index=models.Index(
                fields=["import_record", "was_created"],
                name="banking_imp_import__e0a6c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importtransaction",
            index=models.Index(
                fields=["transaction", "-created_at"],
                name="banking_imp_transac_4a05ac_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="importtransaction",
            unique_together={("import_record", "transaction")},
        ),
    ]
