# Generated by Django 6.0.1 on 2026-01-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0009_import_importtransaction_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("account", "date", "amount", "reference"),
                name="unique_transaction_per_account",
            ),
        ),
    ]
