# Generated by Django 6.0.1 on 2026-01-25 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0010_transaction_unique_transaction_per_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("unusual_amount", "Unusual Amount"),
                            ("unusual_timing", "Unusual Timing"),
                            ("duplicate_pattern", "Duplicate Pattern"),
                            ("missing_recurring", "Missing Recurring Payment"),
                            ("changed_recurring", "Changed Recurring Pattern"),
                            ("spending_spike", "Spending Spike"),
                            ("new_merchant", "New Merchant"),
                            ("account_inactive", "Account Inactive"),
                            ("multiple_failures", "Multiple Failed Transactions"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title of the anomaly", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed explanation of what was detected"
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Why this was flagged as an anomaly"),
                ),
                (
                    "anomaly_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Confidence score 0-100",
                        max_digits=5,
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected value for this anomaly",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual value detected",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "deviation_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Deviation percentage",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata: similar_transactions, historical_average, etc.",
                    ),
                ),
                (
                    "is_dismissed",
                    models.BooleanField(
                        default=False, help_text="Whether user dismissed this anomaly"
                    ),
                ),
                ("dismissed_by_user", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_false_positive",
                    models.BooleanField(
                        default=False, help_text="User marked as false positive"
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False, help_text="User confirmed this anomaly"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "recurring",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="banking.recurringtransaction",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="banking.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_notified_via_email", models.BooleanField(default=False)),
                ("is_notified_via_push", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anomaly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="banking.anomaly",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnomalyPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anomaly_detection_enabled", models.BooleanField(default=True)),
                ("notify_on_critical", models.BooleanField(default=True)),
                ("notify_on_warning", models.BooleanField(default=False)),
                ("notify_on_info", models.BooleanField(default=False)),
                ("email_notifications", models.BooleanField(default=False)),
                ("push_notifications", models.BooleanField(default=True)),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "enabled_types",
                    models.JSONField(
                        default=[
                            "unusual_amount",
                            "missing_recurring",
                            "changed_recurring",
                            "spending_spike",
                        ],
                        help_text="List of anomaly types to detect",
                    ),
                ),
                (
                    "amount_deviation_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        help_text="Amount deviation % threshold (e.g., 50 = 1.5x is anomalous)",
                        max_digits=5,
                    ),
                ),
                (
                    "spending_spike_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        help_text="Spending spike multiplier (e.g., 2 = 2x is anomalous)",
                        max_digits=5,
                    ),
                ),
                (
                    "days_before_inactive",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days without transactions before marking account as inactive",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Anomaly Preferences",
            },
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["user", "-created_at"], name="banking_ano_user_id_5b6e25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["user", "severity"], name="banking_ano_user_id_a3be9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["account", "is_dismissed"],
                name="banking_ano_account_dc2c55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomaly",
            index=models.Index(
                fields=["anomaly_type", "created_at"],
                name="banking_ano_anomaly_1105b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalynotification",
            index=models.Index(
                fields=["user", "-created_at"], name="banking_ano_user_id_cd3195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anomalynotification",
            index=models.Index(
                fields=["user", "is_read"], name="banking_ano_user_id_4899a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anomalynotification",
            constraint=models.UniqueConstraint(
                fields=("user", "anomaly"), name="unique_user_anomaly_notification"
            ),
        ),
    ]
