# Generated by Django 6.0.1 on 2026-01-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0012_remove_unique_constraint_handle_in_importer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useranomalypreferences",
            name="enabled_types",
            field=models.JSONField(
                default=list, help_text="List of anomaly types to detect"
            ),
        ),
    ]
