# Generated by Django 6.0.1 on 2026-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="currency_preference",
            field=models.CharField(
                db_column="currency_preference", default="USD", max_length=8
            ),
        ),
    ]
